apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-observability-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Abeta-dev/cloud-native-observability.git
    targetRevision: v0.2.3
    path: deploy/kubernetes/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
