apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-secrets
  namespace: argocd
  labels:
    tier: observability
    component: secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/umesh0492/cloud-native-observability.git
    targetRevision: v0.1.0
    path: deploy/kubernetes/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
